### ISSUE TITLE
react-admin data provider improvements

### ISSUE THREAD

**Issue by mwarger** [mwarger/nextpo-trpc#3]
react-admin requires a set of specific methods (https://marmelab.com/react-admin/DataProviders.html)

 - assuming it might be possible to map over the routers, and possibly having a router per entity, each could have a react-admin router augmentation that adds the appropriate methods to the routers, ensuring that they exist

- something like https://github.com/trpc/trpc/discussions/714 could be used to grab the appropriate router definition

- research other ra-data providers to see how they accomplish setting up endpoints

**Comment by KATT** [comment]
If you figure this out I'd be curious to get this into zart as well

**Comment by mwarger** [comment]
Some progress...

created `createReactAdminRouter` function to add a set of defaults for a given router.  
Usage:
![image](https://user-images.githubusercontent.com/686823/133011859-4e521be9-038d-4a9e-b8f5-06f98596392b.png)

Created a selector like supabase uses for resources - this affects what is set as `select:true` when using prisma.
![image](https://user-images.githubusercontent.com/686823/133011949-d862841f-a4e5-4dc7-8c36-b01700461054.png)

The DataProvider passes them along...
![image](https://user-images.githubusercontent.com/686823/133012053-35a23301-9a79-4863-bb41-9410800d0fc7.png)

And the router applies them.
![image](https://user-images.githubusercontent.com/686823/133012191-ebdae173-3b4a-420e-a4c1-1ec7ed8968f0.png)

**Comment by KATT** [comment]
Looks like this could become the first plugin for trpc even 

```ts
import {trpcReactAdmin} from 'trpc-react-admin';
import * as trpc from 'trpc';

const tra = trpcReactAdmin({ /* conf */ })


const appRouter = trpc.router().merge(tra.router)/*...*/


const provider = tra.dataProvider // use for react admin
```

**Comment by mwarger** [comment]
first working package version here: https://www.npmjs.com/package/trpc-react-admin

**Comment by mwarger** [comment]
cc @KATT - moved to https://github.com/mwarger/ra-trpc

Happy to add you as a collaborator if you're interested.  :)  Comments/feedback is welcome.
